declare const classNames: {
  readonly imageSelector: "imageSelector";
  readonly imageSelectorLabel: "imageSelectorLabel";
  readonly imageSelectorLabelProcess: "imageSelectorLabelProcess";
  readonly description: "description";
  readonly imageContainer: "imageContainer";
  readonly image: "image";
  readonly imageNormal: "imageNormal";
  readonly imageSelected: "imageSelected";
  readonly fullScreenContainer: "fullScreenContainer";
  readonly fullScreenContainerShow: "fullScreenContainerShow";
  readonly fullScreenContainerHidden: "fullScreenContainerHidden";
  readonly fullScreenImage: "fullScreenImage";
  readonly fullScreenImageBackground: "fullScreenImageBackground";
  readonly imageShow: "imageShow";
  readonly actionContainer: "actionContainer";
  readonly show: "show";
  readonly hidden: "hidden";
};
export = classNames;
